### ISSUE TITLE
Shader are not loaded like is on shadertoy 

### ISSUE THREAD

**Issue by balex25** [mengxipeng1122/shadertoyviewer#1]
Hi, it is possible to import a shader like as?

https://www.shadertoy.com/view/Xl3XzS

I get this result with you viewer:
![notepad++_znlZ4f2IFp](https://user-images.githubusercontent.com/37195461/174402948-e83f54eb-5c54-4466-abe0-d5813108897c.png)

Any help will be appreciated, thanks you  for all work :)

**Comment by mengxipeng1122** [comment]
Added , please check
